agents:
  queue: "carlos"

steps:
  - label: "Go version"
    command: go version
    concurrency_group: buildkite-sample/version
    concurrency: 2
  - label: "Unit test"
    command: go test ./... -v -timeout 1m -count=1
    concurrency_group: buildkite-sample/go-tasks
    concurrency: 1
  - label: "Build"
    command: go build .
    concurrency_group: buildkite-sample/go-tasks
    concurrency: 1
