agents:
  queue: "carlos"

steps:
  - label: "Go version"
    command: go version
    concurrency_group: buildkite-sample/version
    concurrency: 2
  - label: "Go lint"
    command: golangci-lint run ./...
    concurrency: 1
    concurrency_group: buildkite-sample/go-tasks
  - label: "Unit test"
    command: gotestsum --junitfile test.xml
    concurrency_group: buildkite-sample/go-tasks
    concurrency: 1
  - label: "Upload tests to datadog"
    command: DATADOG_API_KEY=$DATADOG_API_KEY DD_ENV=carlos-testing DD_SITE=datad0g.com datadog-ci junit upload --service carlos-test test.xml"
    concurrency_group: buildkite-sample/go-tasks
    concurrency: 1
  - block: "Build"
    prompt: "Testing out stuff"
    fields:
      - text: "Name"
        key: "parameter-name"
  - label: "Get parameters"
    command: buildkite-agent meta-data get "parameter-name"
  - label: "Build"
    command: go build .
    concurrency_group: buildkite-sample/go-tasks
    concurrency: 1
